import { Course } from './types';

export const ALL_COURSES: Course[] = [
    { 
        id: 1, 
        title: 'การสร้างคน ด้วยระบบพี่เลี้ยง และการสอนแนะ', 
        category: 'Learning & Development', 
        type: 'Public Training', 
        format: 'Onsite', 
        date: '30 January 2026', 
        time: '09:00-16:00', 
        location: 'Amari Hotel', 
        instructor: [{ name: 'อ. สมชาย เก่งมาก', image: 'https://randomuser.me/api/portraits/men/32.jpg' }], 
        priceMember: '2,000.00', 
        priceNormal: '2,200.00', 
        status: 'เปิดรับสมัคร', 
        image: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=800&q=80', 
        past: false,
        owner: 'Super Admin'
    },
    { 
        id: 15, 
        title: 'การจัดการทรัพยากรมนุษย์ชั้นต้น (PM) รุ่นที่ 444', 
        category: 'Performance Management', 
        type: 'PM', 
        format: 'Onsite', 
        date: '15-25 November 2026', 
        time: '09:00-16:00', 
        location: 'Centara Grand', 
        instructor: [
            { name: 'อ. วิทวัส ยอดฝีมือ', image: 'https://randomuser.me/api/portraits/men/45.jpg' },
            { name: 'อ. ก', image: 'https://randomuser.me/api/portraits/men/11.jpg' },
            { name: 'อ. ข', image: 'https://randomuser.me/api/portraits/men/12.jpg' },
            { name: 'อ. ค', image: 'https://randomuser.me/api/portraits/men/13.jpg' },
            { name: 'อ. ง', image: 'https://randomuser.me/api/portraits/men/14.jpg' },
            { name: 'อ. จ', image: 'https://randomuser.me/api/portraits/men/15.jpg' },
            { name: 'อ. ฉ', image: 'https://randomuser.me/api/portraits/men/16.jpg' },
            { name: 'อ. ช', image: 'https://randomuser.me/api/portraits/men/17.jpg' },
            { name: 'อ. ซ', image: 'https://randomuser.me/api/portraits/men/18.jpg' }
        ], 
        priceMember: '8,000.00', 
        priceNormal: '8,800.00', 
        status: 'เปิดรับสมัคร', 
        image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80', 
        past: false,
        owner: 'Super Admin'
    },
    { 
        id: 16, 
        title: 'การจัดการทรัพยากรมนุษย์ชั้นlสูง (APM) รุ่นที่ 120', 
        category: 'HR Strategy', 
        type: 'APM', 
        format: 'Onsite', 
        date: '10 - 20 December 2026', 
        time: '09:00-16:00', 
        location: 'The Landmark Hotel', 
        instructor: [
            { name: 'ดร. ชัยชนะ เลิศปัญญา', image: 'https://randomuser.me/api/portraits/men/85.jpg' },
            { name: 'คุณ สมหญิง เก่งกาจ', image: 'https://randomuser.me/api/portraits/women/44.jpg' },
            { name: 'อ. วิชัย มีชัย', image: 'https://randomuser.me/api/portraits/men/22.jpg' },
            { name: 'อ. เอ', image: 'https://randomuser.me/api/portraits/men/60.jpg' },
            { name: 'อ. บี', image: 'https://randomuser.me/api/portraits/women/61.jpg' },
            { name: 'อ. ซี', image: 'https://randomuser.me/api/portraits/men/62.jpg' },
            { name: 'อ. ดี', image: 'https://randomuser.me/api/portraits/women/63.jpg' },
            { name: 'อ. อี', image: 'https://randomuser.me/api/portraits/men/64.jpg' },
            { name: 'อ. เอฟ', image: 'https://randomuser.me/api/portraits/women/65.jpg' }
        ], 
        priceMember: '9,000.00', 
        priceNormal: '9,900.00', 
        status: 'เปิดรับสมัคร', 
        image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=800&q=80', 
        past: false,
        owner: 'Super Admin'
    },
    { 
        id: 17, 
        title: 'องค์กร รมณีย์ รุ่น 14', 
        category: 'Employee Relations', 
        type: 'Mindfulness', 
        format: 'Onsite', 
        date: '30 November 2026', 
        time: '09:00-16:00', 
        location: 'Grande Centre Point', 
        instructor: [
            { name: 'อ. จิตรา เข้าใจ', image: 'https://randomuser.me/api/portraits/women/68.jpg' },
            { name: 'อ. สมศรี มีสุข', image: 'https://randomuser.me/api/portraits/women/33.jpg' },
            { name: 'คุณ ประกอบ กิจการ', image: 'https://randomuser.me/api/portraits/men/75.jpg' },
            { name: 'ดร. บรรลุ เป้าหมาย', image: 'https://randomuser.me/api/portraits/men/55.jpg' }
        ], 
        priceMember: '7,200.00', 
        priceNormal: '7,900.00', 
        status: 'เลื่อน', 
        image: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=800&q=80', 
        past: false,
        owner: 'Super Admin'
    },
    { 
        id: 18, 
        title: 'HR Fundamental Skill รุ่นที่ 20', 
        category: 'Recruitment & Selection', 
        type: 'HR Fundamental', 
        format: 'Online', 
        date: '18 October 2026', 
        time: '09:00-16:00', 
        location: 'Amari Hotel', 
        instructor: [{ name: 'คุณ พัฒนา อบรมดี', image: 'https://randomuser.me/api/portraits/men/36.jpg' }], 
        priceMember: '6,500.00', 
        priceNormal: '7,200.00', 
        status: 'เต็ม', 
        image: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=800&q=80', 
        past: false,
        owner: 'Super Admin'
    },
    { 
        id: 19, 
        title: 'สวัสดิการพนักงานที่ยืดหยุ่นและเลือกได้', 
        category: 'Workforce Planning', 
        type: 'Free', 
        format: 'Online', 
        date: '25 September 2026', 
        time: '09:00-16:00', 
        location: 'Online - Zoom', 
        instructor: [], 
        priceMember: 'ฟรี', 
        priceNormal: '500', 
        status: 'ยกเลิก', 
        image: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=800&q=80', 
        past: false 
    },
    { 
        id: 22, 
        title: 'AI Prompt for HR', 
        category: 'HR Strategy', 
        type: 'Free', 
        format: 'Online', 
        date: '25 December 2026', 
        time: '09:00-16:00', 
        location: 'Online - Zoom', 
        instructor: [], 
        priceMember: 'ฟรี', 
        priceNormal: 'ฟรี', 
        status: 'เปิดรับสมัคร', 
        image: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=800&q=80', 
        past: false 
    },
    { 
        id: 23, 
        title: 'การพัฒนาภาวะผู้นำ', 
        category: 'HR Strategy', 
        type: 'Free', 
        format: 'Onsite', 
        date: '1 September 2026', 
        time: '09:00-16:00', 
        location: 'To be confirmed', 
        instructor: [{ name: 'อ. ผู้นำ ดีเด่น', image: 'https://randomuser.me/api/portraits/men/91.jpg' }], 
        priceMember: 'ฟรี', 
        priceNormal: '-', 
        status: 'เปิดรับสมัคร', 
        image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&q=80', 
        past: false 
    },
    
    // Past courses
    { 
        id: 7, 
        title: 'การสัมภาษณ์งานอย่างมีประสิทธิภาพ', 
        category: 'Recruitment & Selection', 
        type: 'Public Training', 
        format: 'Online', 
        date: '15 July 2025', 
        time: '09:00-16:00', 
        location: 'Online - Zoom', 
        instructor: [{ name: 'อ. พรทิพย์ ยอดเยี่ยม', image: 'https://randomuser.me/api/portraits/women/65.jpg' }], 
        priceMember: '4,500.00', 
        priceNormal: '5,000.00', 
        status: 'จัดไปแล้ว', 
        image: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=800&q=80', 
        past: true 
    },
    { 
        id: 8, 
        title: 'การสร้าง Engagement ในองค์กร', 
        category: 'Employee Relations', 
        type: 'Public Training', 
        format: 'Onsite', 
        date: '01-02 August 2025', 
        time: '09:00-16:00', 
        location: 'Centara Grand', 
        instructor: [{ name: 'คุณ มานพ ตั้งใจ', image: 'https://randomuser.me/api/portraits/men/15.jpg' }], 
        priceMember: '8,900.00', 
        priceNormal: '9,900.00', 
        status: 'จัดไปแล้ว', 
        image: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=800&q=80', 
        past: true 
    },
    { 
        id: 20, 
        title: 'การจัดการทรัพยากรมนุษย์ชั้นต้น (PM) รุ่นที่ 443', 
        category: 'Performance Management', 
        type: 'PM', 
        format: 'Onsite', 
        date: '10-20 May 2025', 
        time: '09:00-16:00', 
        location: 'The Landmark Hotel', 
        instructor: [
            { name: 'อ. ประเมิน ผลดี', image: 'https://randomuser.me/api/portraits/men/28.jpg' },
            { name: 'อ. ก', image: 'https://randomuser.me/api/portraits/men/11.jpg' },
            { name: 'อ. ข', image: 'https://randomuser.me/api/portraits/men/12.jpg' },
            { name: 'อ. ค', image: 'https://randomuser.me/api/portraits/men/13.jpg' },
            { name: 'อ. ง', image: 'https://randomuser.me/api/portraits/men/14.jpg' },
            { name: 'อ. จ', image: 'https://randomuser.me/api/portraits/men/15.jpg' },
            { name: 'อ. ฉ', image: 'https://randomuser.me/api/portraits/men/16.jpg' },
            { name: 'อ. ช', image: 'https://randomuser.me/api/portraits/men/17.jpg' },
            { name: 'อ. ซ', image: 'https://randomuser.me/api/portraits/men/18.jpg' }
        ], 
        priceMember: '7,500.00', 
        priceNormal: '8,200.00', 
        status: 'จัดไปแล้ว', 
        image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=800&q=80', 
        past: true 
    },
    { 
        id: 21, 
        title: 'HR Fundamental Skill รุ่นที่ 19', 
        category: 'Career Management', 
        type: 'HR Fundamental', 
        format: 'Online', 
        date: '22 April 2025', 
        time: '09:00-16:00', 
        location: 'Amari Hotel', 
        instructor: [{ name: 'อ. ก้าวหน้า มั่นคง', image: 'https://randomuser.me/api/portraits/men/52.jpg' }], 
        priceMember: '7,800.00', 
        priceNormal: '8,500.00', 
        status: 'จัดไปแล้ว', 
        image: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=800&q=80', 
        past: true 
    },
];